- app/Http/Controllers/ConsultasController.php
- app/Http/Controllers/ViewsController.php
- resources/views/Guest/Home-Guest.blade.php
- resources/views/User/Carrito-User.blade.php
- resources/views/User/Cursos-User.blade.php
- resources/views/User/Home-usuario.blade.php
- resources/views/User/Reservacion-User.blade.php
- routes/web.php
> [FIX] - Errores visuales

- app/Http/Controllers/ViewsController.php
- resources/views/Boss/Agregar-Descuento-Tecnica.blade.php
- resources/views/Boss/Ver-Descuentos.blade.php
- resources/views/User/Cursos-User.blade.php
- resources/views/User/Historial-User.blade.php
> [FIX] - Cosillas arregladas

- app/Http/Controllers/ViewsController.php
> [FIX] - Vista guest

- app/Http/Controllers/ViewsController.php
- resources/views/errors/404.blade.php
- resources/views/errors/500.blade.php
- routes/web.php
> [FIX] - Ya lo ultimo, lo juro

- resources/views/Guest/Productos-Guest.blade.php
- resources/views/errors/404.blade.php
- resources/views/errors/500.blade.php
> [FIX] - Error guest vista

- app/Http/Controllers/ViewsController.php
- resources/views/errors/404.blade.php
- resources/views/errors/500.blade.php
> [FIX] - Error vista guest en server

- app/Http/Controllers/ViewsController.php
- resources/views/Guest/Productos-Guest.blade.php
- resources/views/errors/404.blade.php
- resources/views/errors/500.blade.php
> [FIX] - Vista guest servidor

- resources/views/Guest/Productos-Guest.blade.php
- routes/web.php
> [FIX] - Guest servidor

- resources/views/Guest/Registro.blade.php
> [FIX] - Genero/registro

- app/Http/Controllers/InscripcionController.php
- app/Http/Controllers/UsuarioController.php
- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Agregar-Descuento-Producto.blade.php
- resources/views/Boss/Agregar-Descuento-Tecnica.blade.php
- resources/views/Boss/Agregar-Empleado.blade.php
- resources/views/Boss/Agregar-Producto.blade.php
- resources/views/Boss/Agregar-Servicio.blade.php
- resources/views/Boss/Agregar-Tecnica.blade.php
- resources/views/Boss/Perfil-Admin.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
- resources/views/Boss/Ver-Descuentos.blade.php
- resources/views/Boss/Ver-Empleados.blade.php
- resources/views/Boss/Ver-Inventario.blade.php
- resources/views/Boss/Ver-Productos.blade.php
- resources/views/Boss/Ver-Servicios.blade.php
- resources/views/User/Perfil-User.blade.php
- routes/web.php
Los administradores ahora podrán rembolsar las inscripciones, al hacer esto se regresarán los productos que necesita una inscripción para funcionar al inventario, además ahora también puede eliminar inscripciones. También se corrigieron algunos errores de funcionalidad.
> [UPD] - Cursos/admin

- app/Http/Controllers/InscripcionController.php
- app/Mail/InscripcionAceptada.php
- resources/views/email/inscripcionaceptada.blade.php
La función para mandar correos una vez aceptados al curso, ha sido agregado con éxito.
> [ADD] - Email curso aceptado

- app/Http/Controllers/InscripcionController.php
- resources/views/Guest/Registro.blade.php
> [FIX] - Conflicto en inscripciones

- app/Http/Controllers/DetalleProductoController.php
- app/Http/Controllers/VentaController.php
- resources/views/Boss/Ver-Ventas.blade.php
- resources/views/User/Carrito-User.blade.php
- routes/web.php
Actualizacion a diferentes aspectos (carrito,ventas,etc)
> Aldebaran alba

- app/Http/Controllers/InventarioController.php
- resources/views/Boss/Ver-Inventario.blade.php
- routes/web.php
> [ADD] - Filtro menor/mayor en inventario

- resources/views/Boss/Agregar-Tecnica.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
- resources/views/Boss/Ver-Inventario.blade.php
- resources/views/Boss/Ver-Servicios.blade.php
- resources/views/User/Historial-User.blade.php
> [FIX] - Filtro en inventario

- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Agregar-Descuento-Tecnica.blade.php
- resources/views/Boss/Ver-Inventario.blade.php
- resources/views/Employee/Agregar-Cita-Empleado.blade.php
- resources/views/Employee/Home-empleado.blade.php
- resources/views/Employee/Ver-Citas-Empleado.blade.php
- resources/views/Employee/Ver-Productos-Empleado.blade.php
Corregí un error el cual hacía poder repetir las técnicas en agregar cursos y agregar descuento en técnica, además le añadí la posibilidad de ver el inventario, mas sin embargo no poder editarlo.
> [FIX] - Técnicas duplicadas y empleado

- app/Http/Controllers/DibujarController.php
- app/Http/Controllers/RegistrosController.php
- resources/views/Boss/Ver-Empleados.blade.php
- resources/views/User/Carrito-User.blade.php
- resources/views/User/Historial-User.blade.php
- resources/views/User/Reservacion-User.blade.php
Eliminar empleado sobre todo, además eliminando las cosas que tenga relación con este. También correo de aviso a empleado y que al hacer citas redirija al historial.
> [FIX] - Eliminar empleado sobre todo

- app/Http/Controllers/RegistrosController.php
- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Agregar-Descuento-Producto.blade.php
- resources/views/Boss/Agregar-Descuento-Tecnica.blade.php
- resources/views/Boss/Agregar-Tecnica.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
- resources/views/Boss/Ver-Descuentos.blade.php
- resources/views/Boss/Ver-Empleados.blade.php
- resources/views/Boss/Ver-Productos.blade.php
- resources/views/Boss/Ver-Servicios.blade.php
> Adrian aldebaran mn

- resources/views/User/Carrito-User.blade.php
- resources/views/User/Historial-User.blade.php
- resources/views/User/Reservacion-User.blade.php
> [FIX] - Es hoy.

- resources/views/User/Carrito-User.blade.php
> Ir a historial al comprar productos

- app/Http/Controllers/ConsultasController.php
- app/Http/Controllers/DibujarController.php
- app/Http/Controllers/InscripcionController.php
- app/Http/Controllers/VentaController.php
- database/migrations/2024_07_01_233725_cursos.php
- database/migrations/2024_07_01_233804_inscripciones.php
- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
- resources/views/Boss/Ver-Ventas.blade.php
- resources/views/User/Carrito-User.blade.php
- resources/views/User/Cursos-User.blade.php
- resources/views/User/Historial-User.blade.php
- routes/web.php
Actualicé los registros, ahora aparecerá si están canceladas las compras, aceptadas, si un curso finalizó o si se canceló la inscripción.
> [UPD] - Historial actualizado

- app/Http/Controllers/DibujarController.php
- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
Ahora no dejará eliminar o editar algún curso cuando tenga inscripciones al curso y además si queda 1 día para que este inicie. Corregí que se duplique la cita como venta en el historial.
> [UPD] - Editar/Borrar cursos

- app/Http/Controllers/InscripcionController.php
- app/Http/Controllers/VentaController.php
- app/Mail/CompraRealizada.php
- app/Mail/InscripcionCancelada.php
- resources/views/Boss/Ver-Reportes.blade.php
- resources/views/email/inscripcionrechazada.blade.php
- resources/views/email/precompra.blade.php
> Adrian aldebaran18

- app/Http/Controllers/ConsultasController.php
- app/Http/Controllers/DibujarController.php
- app/Http/Controllers/InscripcionController.php
- app/Http/Controllers/RegistrosController.php
- app/Models/Curso.php
- app/Models/Inscripcion.php
- database/migrations/2024_07_01_233725_cursos.php
- database/migrations/2024_07_01_233804_inscripciones.php
- resources/views/Boss/Agregar-Curso.blade.php
- resources/views/Boss/Ver-Citas.blade.php
- resources/views/Boss/Ver-Cursos.blade.php
- resources/views/User/Cursos-User.blade.php
- resources/views/User/Historial-User.blade.php
- routes/web.php
- Ahora se mostrarán en una pestaña aparte los cursos que han finalizado, también se podrán mostrar las inscripciones que hasta el final estuvieron aceptadas. Se agregó un atributo nuevo a inscripciones, esto para poder saber cuando un admin eliminó una inscripción manualmente, se pone en true cuando se elimina una inscripción y cuando se finaliza un curso y la inscripción está en pendiente, esto hará que se ponga en true el nuevo atributo, lo utilizo para que solo me dibuje las inscripciones que fueron null pero que no fueron canceladas por admin, o sea que si llegaron hasta el final del curso.
- Ahora los cursos cuentan con 2 fechas que se asignan automáticamente después de añadir la fecha de inicio o editar esta misma, la segunda fecha es un día después de la fecha de inicio, y la …
> [UPD] - Cursos rework

- app/Http/Controllers/RegistrosController.php
- resources/views/Boss/Agregar-Curso.blade.php
Ahora el sistema valida si es que un empleado/admin tiene citas en un lapso de un curso, si es que tiene citas, entonces no lo dejará ser instructor.
> [UPD] - Validación cursos

- app/Http/Controllers/DetalleProductoController.php
- resources/views/Boss/Ver-Ventas.blade.php
- routes/web.php
[UPD] - Historial de ventas rechazadas
> Adrian aldebaran c final

- app/Http/Controllers/DibujarController.php
- resources/views/User/Carrito-User.blade.php
- resources/views/User/Cursos-User.blade.php
- resources/views/User/Historial-User.blade.php
- resources/views/User/Home-usuario.blade.php
- resources/views/User/Perfil-User.blade.php
- resources/views/User/Productos-User.blade.php
- resources/views/User/Reservacion-User.blade.php
- routes/web.php
Ahora se muestra la cantidad de productos que hay en el carrito del usuario logueado, esto se ve al lado del icono del carrito en el navbar, ahora también se puede eliminar todo el carrito con un solo botón.
> [UPD] - Cantidad de productos en carrito

- app/Http/Controllers/DibujarController.php
- resources/views/Boss/Ver-Descuentos.blade.php
- resources/views/Boss/Ver-Inventario.blade.php
- resources/views/Boss/Ver-Productos.blade.php
- resources/views/Boss/Ver-Reportes.blade.php
- resources/views/Boss/Ver-Ventas.blade.php
> Aldebaran20

- resources/views/Boss/Ver-Inventario.blade.php
> [Alerta Inv] UPD
